---
title: "R Notebook"
output: html_notebook
---

```{r}
source('./R/url.R')

my_url <- make_search_url(query = "unconventional")

onepetro_allpages_to_dataframe(my_url)
```

```{r}
source('./R/url.R')

my_url <- make_search_url(query = "heat transfer", how = "all")

onepetro_allpages_to_dataframe(my_url)
```


```{r}
source('./R/url.R')

my_url <- make_search_url(query = "nanodarcy", how = "any")

onepetro_allpages_to_dataframe(my_url)
```




```{r}
source('./R/url.R')

my_url <- make_search_url(query = "algorithm", 
                          how = "all")

onepetro_allpages_to_dataframe(my_url)
```


```{r}
source('./R/url.R')

my_url <- make_search_url(query = "digital", 
                          how = "all")

onepetro_allpages_to_dataframe(my_url)
```

```{r}
source('./R/url.R')

my_url <- make_search_url(query = "digital oilfield", 
                          how = "all")

onepetro_allpages_to_dataframe(my_url)
```

```{r}
source('./R/url.R')

my_url <- make_search_url(query = "intelligent completions", 
                          how = "all")

onepetro_allpages_to_dataframe(my_url)
```



```{r}
source('./R/url.R')

my_url <- make_search_url(query = "oil shale", 
                          how = "all")

onepetro_allpages_to_dataframe(my_url)
```