---
title: "R Notebook"
output: html_notebook
---
https://www.r-bloggers.com/google-scholar-scraping-with-rvest-package/

```{r}
library(rvest)
page <- read_html("https://scholar.google.com/citations?user=sTR9SIQAAAAJ&hl=en&oi=ao")

# Specify the css selector in html_nodes() and extract the text with html_text(). Finally, change the string to numeric using as.numeric().

citations <- page %>% 
  html_nodes ("#gsc_a_b .gsc_a_c") %>% 
  html_text() %>% 
  as.numeric()
```

```{r}
citations
```

```{r}
barplot(citations, main="How many times has each paper been cited?", ylab='Number of citations', col="skyblue", xlab="")
```

```{r}
page <- read_html("https://scholar.google.com/citations?view_op=list_colleagues&hl=en&user=sTR9SIQAAAAJ")
Coauthors = page %>% 
  html_nodes(css=".gsc_1usr_name a") %>% 
  html_text()

Coauthors = as.data.frame(Coauthors)
names(Coauthors) = 'Coauthors'
```

```{r}
Coauthors
```


```{r}
page <- read_html("https://scholar.google.com/citations?view_op=list_colleagues&hl=en&user=sTR9SIQAAAAJ")
citations = page %>% 
  html_nodes(css = ".gsc_1usr_cby") %>% 
  html_text()

citations 
```

```{r}
citations = gsub('Cited by','', citations)
```

```{r}
citations
```


```{r}
page <- read_html("https://scholar.google.com/citations?view_op=list_colleagues&hl=en&user=sTR9SIQAAAAJ")
affilation = page %>% 
  html_nodes(css = ".gsc_1usr_aff") %>% 
  html_text()

affilation = as.data.frame(affilation)
names(affilation)='Affilation'

# Now, let’s create a data frame that consists of coauthors, citations and affilations

cauthors=cbind(Coauthors, citations, affilation)

cauthors 
```

```{r}
library(ggplot2)
cauthors$Coauthors <- factor(cauthors$Coauthors, levels = cauthors$Coauthors[order(cauthors$citations, decreasing=F)])

ggplot(cauthors,aes(Coauthors,citations))+geom_bar(stat="identity", fill="#ff8c1a",size=5)+
theme(axis.title.y   = element_blank())+ylab("# of citations")+
theme(plot.title=element_text(size = 18,colour="blue"), axis.text.y = element_text(colour="grey20",size=12))+
              ggtitle('Citations of his coauthors')+coord_flip()
```

